# Generated by Django 4.0.2 on 2022-02-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_school', '0004_rename_category_content_calss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='calss',
            new_name='clas',
        ),
    ]
