# Generated by Django 4.0.2 on 2022-02-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_school', '0005_rename_calss_content_clas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='clas',
        ),
        migrations.CreateModel(
            name='Pivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_school.class')),
                ('cont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_school.content')),
            ],
        ),
    ]
