# Generated by Django 4.0.2 on 2022-02-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_school', '0006_remove_content_clas_pivot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pivot',
            new_name='ClassPivotContent',
        ),
    ]
