# Generated by Django 4.0.2 on 2022-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_school', '0007_rename_pivot_classpivotcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='img_duty',
        ),
        migrations.RemoveField(
            model_name='explain',
            name='img_duty',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='img_duty',
        ),
        migrations.AddField(
            model_name='content',
            name='img_content',
            field=models.ImageField(blank=True, null=True, upload_to='duty_Summary'),
        ),
    ]
