# Generated by Django 4.0.2 on 2022-02-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_school', '0008_remove_exam_img_duty_remove_explain_img_duty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='img_duty',
        ),
    ]
