# Generated by Django 4.0.2 on 2022-02-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_school', '0009_remove_duty_img_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_school.class'),
        ),
        migrations.DeleteModel(
            name='ClassPivotContent',
        ),
    ]
