# Generated by Django 4.0.2 on 2022-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_school', '0010_content_clas_delete_classpivotcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='duty_file'),
        ),
    ]
